### ISSUE TITLE
LoadError: cannot load such file -- gems/kong-0.3.3/lib/kong/service

### ISSUE THREAD

**Issue by pikislabis** [kontena/kong-client-ruby#33]
When I try to load the last version (0.3.3) of the gem, installed from rubygems, it launches the below error:
```
$ bundle exec rake assets:precompile
rake aborted!
LoadError: cannot load such file -- /Users/x/.rvm/gems/ruby-2.5.0@global/gems/kong-0.3.3/lib/kong/service
/Users/x/.rvm/gems/ruby-2.5.0@global/gems/kong-0.3.3/lib/kong.rb:5:in `require_relative'
/Users/x/.rvm/gems/ruby-2.5.0@global/gems/kong-0.3.3/lib/kong.rb:5:in `<top (required)>'
...
(See full trace by running task with --trace)
```

The file `lib/kong.rb` installed on my machine is pretty different from the one in the repository.

**Comment by nevalla** [comment]
@pikislabis just pushed 0.3.4 version out. Does that solve the issue?

**Comment by pikislabis** [comment]
It works! Thanks for the quick response and solution.
